export type AsnType = 'ISP' | 'Business' | 'Hosting';

const ASN_TYPE_TERMS: Record<AsnType, string[]> = {
    Hosting: [
        'akamai',
        'alibaba',
        'amazon',
        'arubacloud',
        'azure',
        'choopa',
        'cloudflare',
        'contabo',
        'digitalocean',
        'equinix',
        'gigenet',
        'google cloud',
        'hetzner',
        'hostinger',
        'hosthatch',
        'hostkey',
        'hostus',
        'hivelocity',
        'hyperia',
        'iomart',
        'ionos',
        'joesdatacenter',
        'kamatera',
        'leaseweb',
        'linode',
        'liquid web',
        'm247',
        'netcup',
        'oneprovider',
        'oracle',
        'ovh',
        'plusserver',
        'psychz',
        'rackspace',
        'scaleway',
        'selectel',
        'serverius',
        'servers.com',
        'softlayer',
        'strato',
        'upcloud',
        'vultr',
        'worldstream',
    ],
    ISP: [
        'america movil',
        'at&t',
        'maroc telecom',
        'bharti airtel',
        'bell canada',
        'bt group',
        'british telecom',
        'centurylink',
        'charter',
        'china telecom',
        'china unicom',
        'comcast',
        'cox',
        'deutsche telekom',
        'frontier',
        'jio',
        'kddi',
        'liberty global',
        'lumen',
        'ntt',
        'optus',
        'orange',
        'reliance jio',
        'rogers',
        'spectrum',
        'singtel',
        'shaw',
        'sky uk',
        'softbank',
        'swisscom',
        't-mobile',
        'telefonica',
        'telia',
        'telstra',
        'telenet',
        'verizon',
        'vivo',
        'vodafone',
        'virgin media',
    ],
    Business: [],
};

export function getAsnType(holder: string | null | undefined): AsnType {
    const name = (holder ?? '').toLowerCase();

    for (const [type, terms] of Object.entries(ASN_TYPE_TERMS) as [
        AsnType,
        string[],
    ][]) {
        if (terms.some((term) => name.includes(term))) {
            return type;
        }
    }

    return 'Hosting';
}
