export type AsnType = 'ISP' | 'Business' | 'Hosting' | 'Unknown';

const ASN_DATA_URL =
    'https://raw.githubusercontent.com/wavecaptcha/ipopsec/data/data/asn.csv.gz';
const ASN_TYPES = new Set<AsnType>(['ISP', 'Business', 'Hosting', 'Unknown']);
let asnTypesPromise: Promise<Map<number, AsnType>> | undefined;

const ASN_TYPE_TERMS: Record<AsnType, string[]> = {
    Unknown: [],
    Hosting: [
        '10tb',
        '1and1',
        '23media',
        'a2 hosting',
        'accelerated it services',
        'akamai',
        'alibaba cloud',
        'aliyun',
        'amazon',
        'amazon aws',
        'amazon data services',
        'amazon technologies',
        'amazon web services',
        'anexia',
        'aruba cloud',
        'arubacloud',
        'atlantic net',
        'atman',
        'azure',
        'b2 net solutions',
        'beget',
        'binary racks',
        'blazingfast',
        'bluehost',
        'bunnycdn',
        'buyvm',
        'cachefly',
        'cdn77',
        'cdnvideo',
        'centurylink cloud',
        'ceranetworks',
        'choopa',
        'cloud sigma',
        'cloudflare',
        'cloudie',
        'clouding',
        'cloudscale',
        'cloudways',
        'cogent communications',
        'colocation america',
        'colocrossing',
        'combahton',
        'constant company',
        'contabo',
        'core backbone',
        'corespace',
        'crocweb',
        'cyberverse',
        'data camp',
        'datacamp',
        'datapacket',
        'dataweb global',
        'dedipath',
        'digital energy technologies',
        'digital ocean',
        'digitalocean',
        'dinahosting',
        'dreamhost',
        'edgecast',
        'edgeuno',
        'equinix',
        'eukhost',
        'eweka',
        'fastly',
        'fdcservers',
        'first colo',
        'fly.io',
        'frantech',
        'g core labs',
        'gcore',
        'gigenet',
        'global layer',
        'global switch',
        'google cloud',
        'google llc',
        'greencloud',
        'greenhost',
        'gtt communications',
        'heficed',
        'hetzner',
        'hivelocity',
        'host europe',
        'host1plus',
        'host4geeks',
        'hostdime',
        'hostgator',
        'hosthatch',
        'hostinger',
        'hostkey',
        'hostnet',
        'hostnine',
        'hostry',
        'hostus',
        'hurricane electric',
        'hydra communications',
        'hyperia',
        'i3d',
        'ibm cloud',
        'incapsula',
        'inetu',
        'internet vikings',
        'interserver',
        'iomart',
        'ionos',
        'keminet',
        'leaseweb',
        'lightedge',
        'lightnode',
        'limelight networks',
        'linode',
        'liquid web',
        'logicweb',
        'm247',
        'massivegrid',
        'maxihost',
        'melbicom',
        'microsoft azure',
        'misaka network',
        'moack',
        'netactuate',
        'netcup',
        'netinternet',
        'netwise',
        'nextlayer',
        'nforce entertainment',
        'nitrado',
        'nobull networks',
        'nobis technology',
        'oneprovider',
        'online sas',
        'oracle cloud',
        'ovh',
        'ovhcloud',
        'packet host',
        'packetexchange',
        'performive',
        'plusserver',
        'psychz',
        'quadranet',
        'racknerd',
        'rackspace',
        'redstation',
        'reg.ru',
        'reliablesite',
        'retn',
        'servercentral',
        'serverion',
        'serverius',
        'servermania',
        'servers.com',
        'serverspace',
        'sharktech',
        'singlehop',
        'softlayer',
        'stackpath',
        'stark industries solutions',
        'strato',
        'swiftway',
        'tencent cloud',
        'terrahost',
        'tier.net',
        'total server solutions',
        'transip',
        'uk2',
        'unitedlayer',
        'upcloud',
        'velia.net',
        'vercel',
        'vultr',
        'webair',
        'webnx',
        'webzilla',
        'wholesale internet',
        'worldstream',
        'xneelo',
        'yandex cloud',
        'zenlayer',
        'zscaler',
    ],
    ISP: [
        '1&1 versatel',
        'a1 hrvatska',
        'a1 telekom',
        'a1 telecommunications',
        'afrihost',
        'airtel',
        'altice',
        'amaysim',
        'america movil',
        'antelig',
        'asahi net',
        'at&t',
        'aussie broadband',
        'axian telecom',
        'beeline',
        'bell canada',
        'bell mobility',
        'bharti airtel',
        'bouygues telecom',
        'brisanet',
        'british telecom',
        'bsnl',
        'bt group',
        'cable one',
        'cablevision',
        'canalbox',
        'cell c',
        'centurylink',
        'charter communications',
        'china mobile',
        'china netcom',
        'china telecom',
        'china unicom',
        'chunghwa telecom',
        'claro',
        'comcast',
        'consolidated communications',
        'cox communications',
        'digi communications',
        'digicel',
        'dna oyj',
        'du telecom',
        'eir broadband',
        'elisa oyj',
        'etisalat',
        'euskaltel',
        'fastweb',
        'free mobile',
        'free sas',
        'frontier communications',
        'gabon telecom',
        'globe telecom',
        'grande communications',
        'hathway',
        'hkt limited',
        'hutchison',
        'iliad',
        'indosat',
        'inwi',
        'jazztel',
        'jio',
        'kabel deutschland',
        'kddi',
        'kpn',
        'kt corporation',
        'lg uplus',
        'liberty global',
        'liberty latin america',
        'lumen',
        'magyar telekom',
        'maroc telecom',
        'masmovil',
        'megafon',
        'millicom',
        'mobily',
        'mtn',
        'netcologne',
        'netia',
        'nos comunicacoes',
        'ntt communications',
        'ntt docomo',
        'o2 broadband',
        'o2 deutschland',
        'o2 uk',
        'ooredoo',
        'open fiber',
        'optimum',
        'optus',
        'orange belgium',
        'orange france',
        'orange maroc',
        'orange polska',
        'orange romania',
        'orange tunisie',
        'pakistan telecommunication',
        'pldt',
        'proximus',
        'pt telkom',
        'qwest communications',
        'reliance communications',
        'reliance jio',
        'rogers',
        'royal cable',
        'safaricom',
        'salt mobile',
        'sasktel',
        'shaw',
        'singtel',
        'sky broadband',
        'sky uk',
        'softbank',
        'spark new zealand',
        'sprint',
        'starhub',
        'stc',
        'sunrise communications',
        'swisscom',
        'talktalk',
        'tata communications',
        'tata teleservices',
        'tele2',
        'telecom argentina',
        'telecom egypt',
        'telecom italia',
        'telecom malaysia',
        'telefonica',
        'telefonica brasil',
        'telefonica de espana',
        'telefonica germany',
        'telia',
        'telkom indonesia',
        'telkom sa',
        'telenet',
        'telenor',
        'telstra',
        'telus',
        'three ireland',
        'three uk',
        'time warner cable',
        't-mobile',
        'tm net',
        'turk telekom',
        'turkcell',
        'uk broadband',
        'unitel',
        'unitymedia',
        'upc broadband',
        'veon',
        'verizon',
        'videotron',
        'virgin media',
        'vivo',
        'vodacom',
        'vodafone',
        'wind tre',
        'windstream',
        'wow internet',
        'xfinity',
        'zain',
        'ziggo',
    ],
    Business: [],
};

function normalizeAsnHolder(holder: string): string {
    return holder
        .normalize('NFKD')
        .toLowerCase()
        .replace(/&/g, ' and ')
        .replace(/[^a-z0-9]+/g, ' ')
        .replace(/\s+/g, ' ')
        .trim();
}

export function getAsnType(holder: string | null | undefined): AsnType {
    const name = normalizeAsnHolder(holder ?? '');

    for (const type of ['Hosting', 'ISP', 'Business'] as const) {
        if (
            ASN_TYPE_TERMS[type].some((term) =>
                name.includes(normalizeAsnHolder(term)),
            )
        ) {
            return type;
        }
    }

    return 'Unknown';
}

async function loadAsnTypes(): Promise<Map<number, AsnType>> {
    const response = await fetch(ASN_DATA_URL);
    if (!response.ok) {
        throw new Error(
            `ASN classification data lookup failed: HTTP ${response.status}`,
        );
    }

    const decompressed = new Response(
        response.body!.pipeThrough(new DecompressionStream('gzip')),
    );
    const types = new Map<number, AsnType>();
    const lines = (await decompressed.text()).split(/\r?\n/);
    for (const line of lines.slice(1)) {
        const [asnText, type] = line.split(',', 3);
        const asn = Number(asnText);
        if (Number.isSafeInteger(asn) && ASN_TYPES.has(type as AsnType)) {
            types.set(asn, type as AsnType);
        }
    }
    return types;
}

export async function classifyAsn(
    asn: number,
    holder?: string | null,
): Promise<AsnType> {
    const fallback = getAsnType(holder);
    try {
        asnTypesPromise ??= loadAsnTypes();
        const classified = (await asnTypesPromise).get(asn);
        return classified && classified !== 'Unknown' ? classified : fallback;
    } catch {
        return fallback;
    }
}
